theme: minima
author: Luke Kuzmish
email: luke@kuzmish.com
title: cosmastech
description: Technical blog focused on Laravel, PHP, MySQL
url: https://cosmastech.com
logo: https://cosmastech.com/assets/cosmastech_logo.png

#minima variables
github_username:   cosmastech
comments_repo: cosmastech/cosmastech.github.io

# Google Analytics
google_analytics: G-0DQ0ZDHJ5Y

defaults:
  -
    scope:
      path: ""
    values:
      logo: https://cosmastech.com/assets/cosmastech_logo.png
      image:
        path: /assets/cosmastech_logo.png
        height: 100
        width: 100
      social:
        name: Luke Kuzmish
        links:
          - https://www.linkedin.com/in/luke-kuzmish-73a68b205/
          - https://github.com/cosmastech
          - https://www.threads.net/@lukekuzmish
plugins:
  - jemoji
  - jekyll-seo-tag
