theme: minima
author: Luke Kuzmish
email: luke@kuzmish.com
title: cosmastech
description: Technical blog focused on Laravel, PHP, MySQL

#minima variables
github_username:   cosmastech
comments_repo: cosmastech/cosmastech.github.io

plugins:
  - jemoji
